---
title: "Data Transformation"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r include=FALSE}
library(plotly)
library(tidyverse)
library(knitr)
library(rmarkdown)
library(patchwork)
library(ggfittext)
library(ggplotify)
library(Matrix)
library(grid)
```

```{r include=FALSE}
dtgn <- read_delim("./data/2021-03_data_transformation_results_gtex_naive.tsv",
                   delim = "\t", col_names = T)
dtsn <- read_delim("./data/2021-03_data_transformation_results_sra_naive.tsv",
                   delim = "\t", col_names = T)

dtgk <- read_delim("./data/2021-03_data_transformation_results_gtex_knowledge.tsv",
                   delim = "\t", col_names = T)
dtsk <- read_delim("./data/2021-03_data_transformation_results_sra_knowledge.tsv",
                   delim = "\t", col_names = T)
```

```{r include=FALSE}
full_dtgn <- read_delim("./data/2021-03_data_transformation_results_gtex_naive_full_table.tsv",
                   delim = "\t", col_names = T)
full_dtsn <- read_delim("./data/2021-03_data_transformation_results_sra_naive_full_table.tsv",
                   delim = "\t", col_names = T)

full_dtgk <- read_delim("./data/2021-03_data_transformation_results_gtex_knowledge_full_table.tsv",
                   delim = "\t", col_names = T)
full_dtsk <- read_delim("./data/2021-03_data_transformation_results_sra_knowledge_full_table.tsv",
                   delim = "\t", col_names = T)
```

```{r}
all_gn_fig <- full_dtgn %>% 
  ggplot(aes(x = log2_auprc_over_prior, 
             y = reorder(method, log2_auprc_over_prior, FUN = median))) +
  geom_vline(xintercept = 0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.1, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.2, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.3, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.4, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.6, color = "#999999", size = 0.1) +
  geom_boxplot(fill = "lightgray", outlier.shape = NA) +
  labs(x=expression(Log[2](auPRC/prior))) +
  scale_x_continuous(breaks = c(-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6),
                     labels = c("-0.1","0","0.1","0.2","0.3","0.4","0.5","0.6")) +
  theme(panel.background = element_rect(fill = "white"), 
        text = element_text(size = 12),
        axis.title.y = element_blank(),
        plot.margin = margin(0.5,0.5,0.5,0.5))
```

```{r}
all_sn_fig <- full_dtsn %>% 
  ggplot(aes(x = log2_auprc_over_prior, 
             y = reorder(method, log2_auprc_over_prior, FUN = median))) +
  geom_vline(xintercept = -0.1, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.1, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.2, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.3, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.4, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.6, color = "#999999", size = 0.1) +
  geom_boxplot(fill = "lightgray", outlier.shape = NA) +
  labs(x=expression(Log[2](auPRC/prior))) +
  scale_x_continuous(breaks = c(-0.1,0,0.1,0.2,0.3,0.4,0.5,0.6),
                     labels = c("-0.1","0","0.1","0.2","0.3","0.4","0.5","0.6"),
                     limits = c(-0.15, 0.65)) +
  theme(panel.background = element_rect(fill = "white"), 
        text = element_text(size = 12),
        axis.title.y = element_blank(),
        plot.margin = margin(0.5,0.5,0.5,0.5))
```

```{r}
all_gk_fig <- full_dtgk %>% 
  ggplot(aes(x = log2_auprc_over_prior, 
             y = reorder(method, log2_auprc_over_prior, FUN = median))) +
  geom_vline(xintercept = -0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 1.0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 1.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 2,0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 2.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 3.0, color = "#999999", size = 0.1) +
  geom_boxplot(fill = "lightgray", outlier.shape = NA) +
  labs(x=expression(Log[2](auPRC/prior))) +
  scale_x_continuous(breaks = c(-0.5,0,0.5,1.0,1.5,2.0,2.5,3.0),
                     labels = c("-0.5","0","0.5","1.0","1.5","2.0","2.5","3.0")) +
  theme(panel.background = element_rect(fill = "white"), 
        text = element_text(size = 12),
        axis.title.y = element_blank(),
        plot.margin = margin(0.5,0.5,0.5,0.5))
```

```{r}
all_sk_fig <- full_dtsk %>% 
  ggplot(aes(x = log2_auprc_over_prior, 
             y = reorder(method, log2_auprc_over_prior, FUN = median))) +
  geom_vline(xintercept = -0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 0.5, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 1.0, color = "#999999", size = 0.1) +
  geom_vline(xintercept = 1.5, color = "#999999", size = 0.1) +
  geom_boxplot(fill = "lightgray", outlier.shape = NA) +
  labs(x=expression(Log[2](auPRC/prior))) +
  scale_x_continuous(breaks = c(-0.5,0,0.5,1.0,1.5),
                     labels = c("-0.5","0","0.5","1.0","1.5"),
                     limits = c(-0.5, 1.5)) +
  theme(panel.background = element_rect(fill = "white"), 
        text = element_text(size = 12),
        axis.title.y = element_blank(),
        plot.margin = margin(0.5,0.5,0.5,0.5))
```

```{r}
naive_all_fig <- all_gn_fig + all_sn_fig 
```

```{r}
knowledge_all_fig <- all_gk_fig + all_sk_fig 
```

```{r}
ggsave("~/Desktop/naive_all_boxplots.pdf", plot = naive_all_fig, height = 6, width = 10)
ggsave("~/Desktop/knowledge_all_boxplots.pdf", plot = knowledge_all_fig, height = 6, width = 10)
```


