---
title: "heatmap_plots_all"
output: html_document
---
```{r include=FALSE}
library(tidyverse)
library(knitr)
library(rmarkdown)
library(patchwork)
library(ggfittext)
library(pheatmap)
library(ggplotify)
library(Matrix)
library(dichromat)
library(RColorBrewer)
```

```{r include=FALSE}
gnr <- read_delim("../data/2020-03-19_gtex_naive_results.txt",
                    delim = "\t", col_names = T)
gnpr <- read_delim("../data/2020-03-19_prec_recall_gtex_naive_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)
gkr <- read_delim("../data/2020-03-19_gtex_knowledge_results.txt",
                    delim = "\t", col_names = T)
gkpr <- read_delim("../data/2020-03-19_prec_recall_gtex_knowledge_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)
method_codes <- read_delim("../data/2020-03-19_method_codes.txt",
                           delim = "\t", col_names = T)

gnr$method <- gsub("quantile", "QNT", gnr$method)
gnr$method <- gsub("wTO", "WTO", gnr$method)
gnpr$method <- gsub("quantile", "QNT", gnpr$method)
gnpr$method <- gsub("wTO", "WTO", gnpr$method)

gkr$method <- gsub("quantile", "QNT", gkr$method)
gkr$method <- gsub("wTO", "WTO", gkr$method)
gkpr$method <- gsub("quantile", "QNT", gkpr$method)
gkpr$method <- gsub("wTO", "WTO", gkpr$method)

method_codes$method <- gsub("quantile", "QNT", method_codes$method)
method_codes$method <- gsub("wTO", "WTO", method_codes$method)
```

```{r include=FALSE}
methods_gn_auprc_prior <- gnr %>% 
  select(project, tissue, method, log2_auprc_over_prior) %>% 
  spread(key = method, value = log2_auprc_over_prior) %>% 
  select(-project, -tissue)

methods_gn_auroc <- gnr %>% 
  select(project, tissue, method, auROC) %>% 
  spread(key = method, value = auROC) %>% 
  select(-project, -tissue)

methods_gn_pr <- gnpr %>% 
  select(project, tissue, method, log2_precision_over_prior) %>% 
  spread(key = method, value = log2_precision_over_prior) %>% 
  select(-project, -tissue)

methods_gk_auprc_prior <- gkr %>% 
  select(project, tissue, method, log2_auprc_over_prior) %>% 
  spread(key = method, value = log2_auprc_over_prior) %>% 
  select(-project, -tissue) 
  
methods_gk_auroc <- gkr %>% 
  select(project, tissue, method, auROC) %>% 
  spread(key = method, value = auROC) %>% 
  select(-project, -tissue) 

methods_gk_pr <- gkpr %>% 
  select(project, tissue, method, log2_precision_over_prior) %>% 
  spread(key = method, value = log2_precision_over_prior) %>% 
  select(-project, -tissue)
```

```{r include=FALSE}
snr <- read_delim("../data/2020-03-19_sra_naive_results.txt",
                    delim = "\t", col_names = T)
snpr <- read_delim("../data/2020-03-19_prec_recall_sra_naive_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)
skr <- read_delim("../data/2020-03-19_sra_knowledge_results.txt",
                    delim = "\t", col_names = T)
skpr <- read_delim("../data/2020-03-19_prec_recall_sra_knowledge_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)
method_codes <- read_delim("../data/2020-03-19_method_codes.txt",
                           delim = "\t", col_names = T)

snr$method <- gsub("quantile", "QNT", snr$method)
snr$method <- gsub("wTO", "WTO", snr$method)
snpr$method <- gsub("quantile", "QNT", snpr$method)
snpr$method <- gsub("wTO", "WTO", snpr$method)

skr$method <- gsub("quantile", "QNT", skr$method)
skr$method <- gsub("wTO", "WTO", skr$method)
skpr$method <- gsub("quantile", "QNT", skpr$method)
skpr$method <- gsub("wTO", "WTO", skpr$method)

method_codes$method <- gsub("quantile", "QNT", method_codes$method)
method_codes$method <- gsub("wTO", "WTO", method_codes$method)

#remove spinal_cord
snr <- snr %>% filter(tissue != "spinal_cord")
skr <- skr %>% filter(tissue != "spinal_cord")
snpr <- snpr %>% filter(tissue != "spinal_cord")
skpr <- skpr %>% filter(tissue != "spinal_cord")
```

```{r include=FALSE}
methods_sn_auprc_prior <- snr %>% 
  select(project, tissue, method, log2_auprc_over_prior) %>% 
  spread(key = method, value = log2_auprc_over_prior) %>% 
  select(-project, -tissue)

methods_sn_auroc <- snr %>% 
  select(project, tissue, method, auROC) %>% 
  spread(key = method, value = auROC) %>% 
  select(-project, -tissue)

methods_sn_pr <- snpr %>% 
  select(project, tissue, method, log2_precision_over_prior) %>% 
  spread(key = method, value = log2_precision_over_prior) %>% 
  select(-project, -tissue)

methods_sk_auprc_prior <- skr %>% 
  select(project, tissue, method, log2_auprc_over_prior) %>% 
  spread(key = method, value = log2_auprc_over_prior) %>% 
  select(-project, -tissue) 
  
methods_sk_auroc <- skr %>% 
  select(project, tissue, method, auROC) %>% 
  spread(key = method, value = auROC) %>% 
  select(-project, -tissue) 

methods_sk_pr <- skpr %>% 
  select(project, tissue, method, log2_precision_over_prior) %>% 
  spread(key = method, value = log2_precision_over_prior) %>% 
  select(-project, -tissue)
```

# Functions
```{r include=FALSE}
#functions to build heatmap
get_times_greater_than_matrix <- function(meth_df){
  #df should be methods_* df (each row is performance on given dataset)
  counts_output <- matrix(rep(0, 900), nrow = 30, ncol = 30)
  colnames(counts_output) <- colnames(meth_df)
  rownames(counts_output) <- colnames(meth_df)
  
  for(num in 1:30){
  a <- pull(meth_df, num)
  for(val in 1:30){
    if (num == val){
      counts_output[val, num] <- 0.5
      next
    }
    b <- pull(meth_df, val)
    s <- sum(a < b)
    s <- s/nrow(meth_df)
    counts_output[val, num] <- s
  }
  }
  return(counts_output)
}

get_significance_matrix <- function(df, performance_col_position, method_col_position){
  #df tidy format with method as a column and performance as a column
  sig_output <- pairwise.wilcox.test(x = pull(df, performance_col_position),
                                     g = pull(df, method_col_position),
                                     paired = TRUE,
                                     p.adjust.method = "BH")$p.value
  
  #add row/col to make 30 by 30
  CLR <- sig_output[1,]
  CLR[1] <- NA
  sig_output <- rbind(CLR, sig_output)
  WTO <- sig_output[,29]
  WTO[30] <- NA
  sig_output <- cbind(sig_output, WTO)
  
  #make symmetric
  diag(sig_output) <- 1
  sig_output <- Matrix::forceSymmetric(sig_output, uplo = "L")
  sig_output <- as.matrix(sig_output)
  #replace p vals with sig/not sig
  sig_wilcox_gtex_naive <- ifelse(sig_output < 0.01, "*", " ")
}

get_method_times_sig_greater <- function(times_matrix, sig_matrix){
  #times_matrix is output of get_times_greater_than_matrix
  #sig_matrix is output of get_significance_matrix
  #make times_matrix into tibble and get times method_one > method_two
  times_greater_than_tibble <- as_tibble(times_matrix)
  times_greater_than_tibble$method_one <- colnames(times_matrix)
  times_greater_than_tibble <- times_greater_than_tibble %>% 
    gather(key = method_two, value = times_method_one_is_greater_than_method_two, 1:30)
  #make sig_matrix into tibble and get times corrected wilcox p value was
  #significant between method_one and method_two
  sig_wilcox_tibble <-  as_tibble(sig_matrix)
  sig_wilcox_tibble$method_one <- colnames(sig_matrix)
  sig_wilcox_tibble <- sig_wilcox_tibble %>%
    gather(key = method_two, value = significance, 1:30)
  sig_wilcox_tibble$significance <- ifelse(sig_wilcox_tibble$significance == "*",
                                           T, F)
  
  #join above two tibbles into one
  greater_than_significance_tibble <- left_join(times_greater_than_tibble,
                                                sig_wilcox_tibble,
                                                by = c("method_one", "method_two"))
  #make T/F column designating whether method_one > method_two AND significant by 
  #corrected wilcox p value
  greater_than_significance_tibble$method_one_greater_than_and_sig <-
    ifelse(greater_than_significance_tibble$times_method_one_is_greater_than_method_two > 0.5 &
       greater_than_significance_tibble$significance == T, T, F)
  #summarize above info by method
  method_summary <- greater_than_significance_tibble %>%
    group_by(method_one) %>% 
    summarise(times_sig_and_greater = sum(method_one_greater_than_and_sig))
  #change col name from method_one to method
  colnames(method_summary) <- c("method", "times_sig_and_greater")
  
  return(method_summary)
}

get_heatmap_order <- function(method_summary, times_mat){
  #times_matrix is output of get_times_greater_than_matrix
  #method_summary is output of get_method_times_sig_greater
  heatmap_row_redness <- Matrix::rowSums(times_mat)
  heatmap_row_redness <- stack(heatmap_row_redness)
  colnames(heatmap_row_redness) <- c("rowsum", "method")
  heatmap_row_redness$rowsum <- as.numeric(heatmap_row_redness$rowsum)
  heatmap_row_redness$method <- as.character(heatmap_row_redness$method)
  method_summary <- left_join(method_summary, heatmap_row_redness, by = "method")
  heatmap_order <- method_summary %>% 
    arrange(desc(times_sig_and_greater), desc(rowsum)) %>% pull(method)
  return(heatmap_order)
}
```

```{r include=FALSE}
heatmap_legend_palette <- colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(101)
r <- tibble(y = rep(1, 101), x = seq(from = 0, to = 1, by = 0.01))
heatmap_legend_all <- ggplot(r, aes(y=y, x=factor(x), fill = factor(x))) +
  geom_tile(height = 0.5) +
  scale_fill_manual(values = heatmap_legend_palette) +
  scale_x_discrete(breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1), labels = c("0", "0.2", "0.4", "0.6", "0.8", "1")) +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(vjust = 2, size = 14, face = "bold"),
        plot.margin = margin(0.5,0.5,0.5,0.5),
        legend.position = "none")
```

# GTEx
## log<sub>2</sub>(auPRC/prior)
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
l2_auprc_prior_naive_times_mat <- get_times_greater_than_matrix(methods_gn_auprc_prior)
l2_auprc_prior_naive_sig_mat <- get_significance_matrix(df = gnr, performance_col_position = 4, method_col_position = 3)
l2_auprc_prior_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_auprc_prior_naive_times_mat,
                                                                                  sig_matrix = l2_auprc_prior_naive_sig_mat)
l2_auprc_prior_naive_heatmap_order <- get_heatmap_order(method_summary = l2_auprc_prior_naive_method_num_times_sig_greater,
                                                        times_mat = l2_auprc_prior_naive_times_mat)
#reorder matrices by heatmap order
l2_auprc_prior_naive_times_mat <- l2_auprc_prior_naive_times_mat[l2_auprc_prior_naive_heatmap_order,]
l2_auprc_prior_naive_times_mat <- l2_auprc_prior_naive_times_mat[,l2_auprc_prior_naive_heatmap_order]
l2_auprc_prior_naive_sig_mat <- l2_auprc_prior_naive_sig_mat[l2_auprc_prior_naive_heatmap_order,]
l2_auprc_prior_naive_sig_mat <- l2_auprc_prior_naive_sig_mat[,l2_auprc_prior_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
l2_auprc_prior_knowledge_times_mat <- get_times_greater_than_matrix(methods_gk_auprc_prior)
l2_auprc_prior_knowledge_sig_mat <- get_significance_matrix(df = gkr, performance_col_position = 4, method_col_position = 3)
l2_auprc_prior_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_auprc_prior_knowledge_times_mat,
                                                                                      sig_matrix = l2_auprc_prior_knowledge_sig_mat)
l2_auprc_prior_knowledge_heatmap_order <- get_heatmap_order(method_summary = l2_auprc_prior_knowledge_method_num_times_sig_greater,
                                                            times_mat = l2_auprc_prior_knowledge_times_mat)
#reorder matrices by heatmap order
l2_auprc_prior_knowledge_times_mat <- l2_auprc_prior_knowledge_times_mat[l2_auprc_prior_knowledge_heatmap_order,]
l2_auprc_prior_knowledge_times_mat <- l2_auprc_prior_knowledge_times_mat[,l2_auprc_prior_knowledge_heatmap_order]
l2_auprc_prior_knowledge_sig_mat <- l2_auprc_prior_knowledge_sig_mat[l2_auprc_prior_knowledge_heatmap_order,]
l2_auprc_prior_knowledge_sig_mat <- l2_auprc_prior_knowledge_sig_mat[,l2_auprc_prior_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
l2_auprc_prior_naive_heatmap <- pheatmap(l2_auprc_prior_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_auprc_prior_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_auprc_prior_naive_heatmap <- as.ggplot(l2_auprc_prior_naive_heatmap)

l2_auprc_prior_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_auprc_prior_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_auprc_prior_naive_bar_plot <- l2_auprc_prior_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_auprc_prior_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
l2_auprc_prior_naive_overall_right_half <- ((l2_auprc_prior_naive_row_labels + l2_auprc_prior_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_auprc_prior_naive_overall_heatmap_fig <- l2_auprc_prior_naive_heatmap + l2_auprc_prior_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/l2_auprc_prior_naive_overall_heatmap_fig.png", 
       plot = l2_auprc_prior_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
l2_auprc_prior_knowledge_heatmap <- pheatmap(l2_auprc_prior_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_auprc_prior_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_auprc_prior_knowledge_heatmap <- as.ggplot(l2_auprc_prior_knowledge_heatmap)

l2_auprc_prior_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_auprc_prior_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_auprc_prior_knowledge_bar_plot <- l2_auprc_prior_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_auprc_prior_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
l2_auprc_prior_knowledge_overall_right_half <- ((l2_auprc_prior_knowledge_row_labels + l2_auprc_prior_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_auprc_prior_knowledge_overall_heatmap_fig <- l2_auprc_prior_knowledge_heatmap + l2_auprc_prior_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/l2_auprc_prior_knowledge_overall_heatmap_fig.png", 
       plot = l2_auprc_prior_knowledge_overall_heatmap_fig, width = 18, height = 9)
```

## auROC
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
auroc_naive_times_mat <- get_times_greater_than_matrix(methods_gn_auroc)
auroc_naive_sig_mat <- get_significance_matrix(df = gnr, performance_col_position = 5, method_col_position = 3)
auroc_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = auroc_naive_times_mat,
                                                                                  sig_matrix = auroc_naive_sig_mat)
auroc_naive_heatmap_order <- get_heatmap_order(method_summary = auroc_naive_method_num_times_sig_greater,
                                                        times_mat = auroc_naive_times_mat)
#reorder matrices by heatmap order
auroc_naive_times_mat <- auroc_naive_times_mat[auroc_naive_heatmap_order,]
auroc_naive_times_mat <- auroc_naive_times_mat[,auroc_naive_heatmap_order]
auroc_naive_sig_mat <- auroc_naive_sig_mat[auroc_naive_heatmap_order,]
auroc_naive_sig_mat <- auroc_naive_sig_mat[,auroc_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
auroc_knowledge_times_mat <- get_times_greater_than_matrix(methods_gk_auroc)
auroc_knowledge_sig_mat <- get_significance_matrix(df = gkr, performance_col_position = 6, method_col_position = 3)
auroc_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = auroc_knowledge_times_mat,
                                                                                      sig_matrix = auroc_knowledge_sig_mat)
auroc_knowledge_heatmap_order <- get_heatmap_order(method_summary = auroc_knowledge_method_num_times_sig_greater,
                                                            times_mat = auroc_knowledge_times_mat)
#reorder matrices by heatmap order
auroc_knowledge_times_mat <- auroc_knowledge_times_mat[auroc_knowledge_heatmap_order,]
auroc_knowledge_times_mat <- auroc_knowledge_times_mat[,auroc_knowledge_heatmap_order]
auroc_knowledge_sig_mat <- auroc_knowledge_sig_mat[auroc_knowledge_heatmap_order,]
auroc_knowledge_sig_mat <- auroc_knowledge_sig_mat[,auroc_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
auroc_naive_heatmap <- pheatmap(auroc_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = auroc_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
auroc_naive_heatmap <- as.ggplot(auroc_naive_heatmap)

auroc_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(auroc_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
auroc_naive_bar_plot <- auroc_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(auroc_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
auroc_naive_overall_right_half <- ((auroc_naive_row_labels + auroc_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
auroc_naive_overall_heatmap_fig <- auroc_naive_heatmap + auroc_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/auroc_naive_overall_heatmap_fig.png", 
       plot = auroc_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
auroc_knowledge_heatmap <- pheatmap(auroc_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = auroc_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
auroc_knowledge_heatmap <- as.ggplot(auroc_knowledge_heatmap)

auroc_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(auroc_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
auroc_knowledge_bar_plot <- auroc_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(auroc_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
auroc_knowledge_overall_right_half <- ((auroc_knowledge_row_labels + auroc_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
auroc_knowledge_overall_heatmap_fig <- auroc_knowledge_heatmap + auroc_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/auroc_knowledge_overall_heatmap_fig.png", 
       plot = auroc_knowledge_overall_heatmap_fig, width = 18, height = 9)
```

## log<sub>2</sub>(precision/prior) at 20% recall
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
l2_prec_at_recall20_naive_times_mat <- get_times_greater_than_matrix(methods_gn_pr)
l2_prec_at_recall20_naive_sig_mat <- get_significance_matrix(df = gnpr, performance_col_position = 7, method_col_position = 3)
l2_prec_at_recall20_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_prec_at_recall20_naive_times_mat,
                                                                                  sig_matrix = l2_prec_at_recall20_naive_sig_mat)
l2_prec_at_recall20_naive_heatmap_order <- get_heatmap_order(method_summary = l2_prec_at_recall20_naive_method_num_times_sig_greater,
                                                        times_mat = l2_prec_at_recall20_naive_times_mat)
#reorder matrices by heatmap order
l2_prec_at_recall20_naive_times_mat <- l2_prec_at_recall20_naive_times_mat[l2_prec_at_recall20_naive_heatmap_order,]
l2_prec_at_recall20_naive_times_mat <- l2_prec_at_recall20_naive_times_mat[,l2_prec_at_recall20_naive_heatmap_order]
l2_prec_at_recall20_naive_sig_mat <- l2_prec_at_recall20_naive_sig_mat[l2_prec_at_recall20_naive_heatmap_order,]
l2_prec_at_recall20_naive_sig_mat <- l2_prec_at_recall20_naive_sig_mat[,l2_prec_at_recall20_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
l2_prec_at_recall20_knowledge_times_mat <- get_times_greater_than_matrix(methods_gk_pr)
l2_prec_at_recall20_knowledge_sig_mat <- get_significance_matrix(df = gkpr, performance_col_position = 10, method_col_position = 3)
l2_prec_at_recall20_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_prec_at_recall20_knowledge_times_mat,
                                                                                      sig_matrix = l2_prec_at_recall20_knowledge_sig_mat)
l2_prec_at_recall20_knowledge_heatmap_order <- get_heatmap_order(method_summary = l2_prec_at_recall20_knowledge_method_num_times_sig_greater,
                                                            times_mat = l2_prec_at_recall20_knowledge_times_mat)
#reorder matrices by heatmap order
l2_prec_at_recall20_knowledge_times_mat <- l2_prec_at_recall20_knowledge_times_mat[l2_prec_at_recall20_knowledge_heatmap_order,]
l2_prec_at_recall20_knowledge_times_mat <- l2_prec_at_recall20_knowledge_times_mat[,l2_prec_at_recall20_knowledge_heatmap_order]
l2_prec_at_recall20_knowledge_sig_mat <- l2_prec_at_recall20_knowledge_sig_mat[l2_prec_at_recall20_knowledge_heatmap_order,]
l2_prec_at_recall20_knowledge_sig_mat <- l2_prec_at_recall20_knowledge_sig_mat[,l2_prec_at_recall20_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
l2_prec_at_recall20_naive_heatmap <- pheatmap(l2_prec_at_recall20_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_prec_at_recall20_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_prec_at_recall20_naive_heatmap <- as.ggplot(l2_prec_at_recall20_naive_heatmap)

l2_prec_at_recall20_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_prec_at_recall20_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_prec_at_recall20_naive_bar_plot <- l2_prec_at_recall20_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_prec_at_recall20_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
l2_prec_at_recall20_naive_overall_right_half <- ((l2_prec_at_recall20_naive_row_labels + l2_prec_at_recall20_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_prec_at_recall20_naive_overall_heatmap_fig <- l2_prec_at_recall20_naive_heatmap + l2_prec_at_recall20_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/l2_prec_at_recall20_naive_overall_heatmap_fig.png", 
       plot = l2_prec_at_recall20_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
l2_prec_at_recall20_knowledge_heatmap <- pheatmap(l2_prec_at_recall20_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_prec_at_recall20_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_prec_at_recall20_knowledge_heatmap <- as.ggplot(l2_prec_at_recall20_knowledge_heatmap)

l2_prec_at_recall20_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_prec_at_recall20_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_prec_at_recall20_knowledge_bar_plot <- l2_prec_at_recall20_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_prec_at_recall20_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
l2_prec_at_recall20_knowledge_overall_right_half <- ((l2_prec_at_recall20_knowledge_row_labels + l2_prec_at_recall20_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_prec_at_recall20_knowledge_overall_heatmap_fig <- l2_prec_at_recall20_knowledge_heatmap + l2_prec_at_recall20_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/l2_prec_at_recall20_knowledge_overall_heatmap_fig.png", 
       plot = l2_prec_at_recall20_knowledge_overall_heatmap_fig, width = 18, height = 9)
```

# SRA
## log<sub>2</sub>(auPRC/prior)
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
l2_auprc_prior_naive_times_mat <- get_times_greater_than_matrix(methods_sn_auprc_prior)
l2_auprc_prior_naive_sig_mat <- get_significance_matrix(df = snr, performance_col_position = 4, method_col_position = 3)
l2_auprc_prior_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_auprc_prior_naive_times_mat,
                                                                                  sig_matrix = l2_auprc_prior_naive_sig_mat)
l2_auprc_prior_naive_heatmap_order <- get_heatmap_order(method_summary = l2_auprc_prior_naive_method_num_times_sig_greater,
                                                        times_mat = l2_auprc_prior_naive_times_mat)
#reorder matrices by heatmap order
l2_auprc_prior_naive_times_mat <- l2_auprc_prior_naive_times_mat[l2_auprc_prior_naive_heatmap_order,]
l2_auprc_prior_naive_times_mat <- l2_auprc_prior_naive_times_mat[,l2_auprc_prior_naive_heatmap_order]
l2_auprc_prior_naive_sig_mat <- l2_auprc_prior_naive_sig_mat[l2_auprc_prior_naive_heatmap_order,]
l2_auprc_prior_naive_sig_mat <- l2_auprc_prior_naive_sig_mat[,l2_auprc_prior_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
l2_auprc_prior_knowledge_times_mat <- get_times_greater_than_matrix(methods_sk_auprc_prior)
l2_auprc_prior_knowledge_sig_mat <- get_significance_matrix(df = skr, performance_col_position = 4, method_col_position = 3)
l2_auprc_prior_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_auprc_prior_knowledge_times_mat,
                                                                                      sig_matrix = l2_auprc_prior_knowledge_sig_mat)
l2_auprc_prior_knowledge_heatmap_order <- get_heatmap_order(method_summary = l2_auprc_prior_knowledge_method_num_times_sig_greater,
                                                            times_mat = l2_auprc_prior_knowledge_times_mat)
#reorder matrices by heatmap order
l2_auprc_prior_knowledge_times_mat <- l2_auprc_prior_knowledge_times_mat[l2_auprc_prior_knowledge_heatmap_order,]
l2_auprc_prior_knowledge_times_mat <- l2_auprc_prior_knowledge_times_mat[,l2_auprc_prior_knowledge_heatmap_order]
l2_auprc_prior_knowledge_sig_mat <- l2_auprc_prior_knowledge_sig_mat[l2_auprc_prior_knowledge_heatmap_order,]
l2_auprc_prior_knowledge_sig_mat <- l2_auprc_prior_knowledge_sig_mat[,l2_auprc_prior_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
l2_auprc_prior_naive_heatmap <- pheatmap(l2_auprc_prior_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_auprc_prior_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_auprc_prior_naive_heatmap <- as.ggplot(l2_auprc_prior_naive_heatmap)

l2_auprc_prior_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_auprc_prior_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_auprc_prior_naive_bar_plot <- l2_auprc_prior_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_auprc_prior_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
l2_auprc_prior_naive_overall_right_half <- ((l2_auprc_prior_naive_row_labels + l2_auprc_prior_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_auprc_prior_naive_overall_heatmap_fig <- l2_auprc_prior_naive_heatmap + l2_auprc_prior_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_l2_auprc_prior_naive_overall_heatmap_fig.png", 
       plot = l2_auprc_prior_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
l2_auprc_prior_knowledge_heatmap <- pheatmap(l2_auprc_prior_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_auprc_prior_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_auprc_prior_knowledge_heatmap <- as.ggplot(l2_auprc_prior_knowledge_heatmap)

l2_auprc_prior_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_auprc_prior_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_auprc_prior_knowledge_bar_plot <- l2_auprc_prior_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_auprc_prior_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
l2_auprc_prior_knowledge_overall_right_half <- ((l2_auprc_prior_knowledge_row_labels + l2_auprc_prior_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_auprc_prior_knowledge_overall_heatmap_fig <- l2_auprc_prior_knowledge_heatmap + l2_auprc_prior_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_l2_auprc_prior_knowledge_overall_heatmap_fig.png", 
       plot = l2_auprc_prior_knowledge_overall_heatmap_fig, width = 18, height = 9)
```

## auROC
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
auroc_naive_times_mat <- get_times_greater_than_matrix(methods_sn_auroc)
auroc_naive_sig_mat <- get_significance_matrix(df = snr, performance_col_position = 5, method_col_position = 3)
auroc_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = auroc_naive_times_mat,
                                                                                  sig_matrix = auroc_naive_sig_mat)
auroc_naive_heatmap_order <- get_heatmap_order(method_summary = auroc_naive_method_num_times_sig_greater,
                                                        times_mat = auroc_naive_times_mat)
#reorder matrices by heatmap order
auroc_naive_times_mat <- auroc_naive_times_mat[auroc_naive_heatmap_order,]
auroc_naive_times_mat <- auroc_naive_times_mat[,auroc_naive_heatmap_order]
auroc_naive_sig_mat <- auroc_naive_sig_mat[auroc_naive_heatmap_order,]
auroc_naive_sig_mat <- auroc_naive_sig_mat[,auroc_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
auroc_knowledge_times_mat <- get_times_greater_than_matrix(methods_sk_auroc)
auroc_knowledge_sig_mat <- get_significance_matrix(df = skr, performance_col_position = 6, method_col_position = 3)
auroc_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = auroc_knowledge_times_mat,
                                                                                      sig_matrix = auroc_knowledge_sig_mat)
auroc_knowledge_heatmap_order <- get_heatmap_order(method_summary = auroc_knowledge_method_num_times_sig_greater,
                                                            times_mat = auroc_knowledge_times_mat)
#reorder matrices by heatmap order
auroc_knowledge_times_mat <- auroc_knowledge_times_mat[auroc_knowledge_heatmap_order,]
auroc_knowledge_times_mat <- auroc_knowledge_times_mat[,auroc_knowledge_heatmap_order]
auroc_knowledge_sig_mat <- auroc_knowledge_sig_mat[auroc_knowledge_heatmap_order,]
auroc_knowledge_sig_mat <- auroc_knowledge_sig_mat[,auroc_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
auroc_naive_heatmap <- pheatmap(auroc_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = auroc_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
auroc_naive_heatmap <- as.ggplot(auroc_naive_heatmap)

auroc_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(auroc_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
auroc_naive_bar_plot <- auroc_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(auroc_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
auroc_naive_overall_right_half <- ((auroc_naive_row_labels + auroc_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
auroc_naive_overall_heatmap_fig <- auroc_naive_heatmap + auroc_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_auroc_naive_overall_heatmap_fig.png", 
       plot = auroc_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
auroc_knowledge_heatmap <- pheatmap(auroc_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = auroc_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
auroc_knowledge_heatmap <- as.ggplot(auroc_knowledge_heatmap)

auroc_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(auroc_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
auroc_knowledge_bar_plot <- auroc_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(auroc_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
auroc_knowledge_overall_right_half <- ((auroc_knowledge_row_labels + auroc_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
auroc_knowledge_overall_heatmap_fig <- auroc_knowledge_heatmap + auroc_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_auroc_knowledge_overall_heatmap_fig.png", 
       plot = auroc_knowledge_overall_heatmap_fig, width = 18, height = 9)
```

## log<sub>2</sub>(precision/prior) at 20% recall
```{r include=FALSE}
#get matrices/tibble/heatmap order for naive plot
l2_prec_at_recall20_naive_times_mat <- get_times_greater_than_matrix(methods_sn_pr)
l2_prec_at_recall20_naive_sig_mat <- get_significance_matrix(df = snpr, performance_col_position = 7, method_col_position = 3)
l2_prec_at_recall20_naive_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_prec_at_recall20_naive_times_mat,
                                                                                  sig_matrix = l2_prec_at_recall20_naive_sig_mat)
l2_prec_at_recall20_naive_heatmap_order <- get_heatmap_order(method_summary = l2_prec_at_recall20_naive_method_num_times_sig_greater,
                                                        times_mat = l2_prec_at_recall20_naive_times_mat)
#reorder matrices by heatmap order
l2_prec_at_recall20_naive_times_mat <- l2_prec_at_recall20_naive_times_mat[l2_prec_at_recall20_naive_heatmap_order,]
l2_prec_at_recall20_naive_times_mat <- l2_prec_at_recall20_naive_times_mat[,l2_prec_at_recall20_naive_heatmap_order]
l2_prec_at_recall20_naive_sig_mat <- l2_prec_at_recall20_naive_sig_mat[l2_prec_at_recall20_naive_heatmap_order,]
l2_prec_at_recall20_naive_sig_mat <- l2_prec_at_recall20_naive_sig_mat[,l2_prec_at_recall20_naive_heatmap_order]

#getmatrices/tibble/heatmap order for knowledge plot
l2_prec_at_recall20_knowledge_times_mat <- get_times_greater_than_matrix(methods_sk_pr)
l2_prec_at_recall20_knowledge_sig_mat <- get_significance_matrix(df = skpr, performance_col_position = 10, method_col_position = 3)
l2_prec_at_recall20_knowledge_method_num_times_sig_greater <- get_method_times_sig_greater(times_matrix = l2_prec_at_recall20_knowledge_times_mat,
                                                                                      sig_matrix = l2_prec_at_recall20_knowledge_sig_mat)
l2_prec_at_recall20_knowledge_heatmap_order <- get_heatmap_order(method_summary = l2_prec_at_recall20_knowledge_method_num_times_sig_greater,
                                                            times_mat = l2_prec_at_recall20_knowledge_times_mat)
#reorder matrices by heatmap order
l2_prec_at_recall20_knowledge_times_mat <- l2_prec_at_recall20_knowledge_times_mat[l2_prec_at_recall20_knowledge_heatmap_order,]
l2_prec_at_recall20_knowledge_times_mat <- l2_prec_at_recall20_knowledge_times_mat[,l2_prec_at_recall20_knowledge_heatmap_order]
l2_prec_at_recall20_knowledge_sig_mat <- l2_prec_at_recall20_knowledge_sig_mat[l2_prec_at_recall20_knowledge_heatmap_order,]
l2_prec_at_recall20_knowledge_sig_mat <- l2_prec_at_recall20_knowledge_sig_mat[,l2_prec_at_recall20_knowledge_heatmap_order]
```

```{r include=FALSE}
#naive plot parts
l2_prec_at_recall20_naive_heatmap <- pheatmap(l2_prec_at_recall20_naive_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_prec_at_recall20_naive_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_prec_at_recall20_naive_heatmap <- as.ggplot(l2_prec_at_recall20_naive_heatmap)

l2_prec_at_recall20_naive_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_prec_at_recall20_naive_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_prec_at_recall20_naive_bar_plot <- l2_prec_at_recall20_naive_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_prec_at_recall20_naive_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#naive plot
l2_prec_at_recall20_naive_overall_right_half <- ((l2_prec_at_recall20_naive_row_labels + l2_prec_at_recall20_naive_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_prec_at_recall20_naive_overall_heatmap_fig <- l2_prec_at_recall20_naive_heatmap + l2_prec_at_recall20_naive_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_l2_prec_at_recall20_naive_overall_heatmap_fig.png", 
       plot = l2_prec_at_recall20_naive_overall_heatmap_fig, width = 18, height = 9)
```

```{r include=FALSE}
#knowledge plot parts
l2_prec_at_recall20_knowledge_heatmap <- pheatmap(l2_prec_at_recall20_knowledge_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = l2_prec_at_recall20_knowledge_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
#change heatmap to ggobject
l2_prec_at_recall20_knowledge_heatmap <- as.ggplot(l2_prec_at_recall20_knowledge_heatmap)

l2_prec_at_recall20_knowledge_row_labels <- method_codes %>% 
  ggplot(aes(x = key, y = factor(method, levels = rev(l2_prec_at_recall20_knowledge_heatmap_order)), fill = value, label = value))+
  geom_tile(color = "white", size = 0.5) +
  #geom_text(aes(label = value)) +
  scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0,5,0)) +
  geom_fit_text() +
  guides(fill = F)
 
l2_prec_at_recall20_knowledge_bar_plot <- l2_prec_at_recall20_knowledge_method_num_times_sig_greater %>% 
  ggplot(aes(x = factor(method, levels = rev(l2_prec_at_recall20_knowledge_heatmap_order)), y = times_sig_and_greater)) +
  geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
  geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
  geom_col(fill = "lightgray") +
  xlab("Method") +
  ylab("Times Significantly Greater Than Other Methods") +
  geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
  scale_y_continuous(limits = c(0,30))+
  coord_flip() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.minor = element_blank(), 
        panel.grid.major = element_blank(),
        text = element_text(size = 14),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(2,0.5,5,0.5)) +
  guides(fill = F)
```

```{r echo=FALSE}
#knowledge plot
l2_prec_at_recall20_knowledge_overall_right_half <- ((l2_prec_at_recall20_knowledge_row_labels + l2_prec_at_recall20_knowledge_bar_plot) / (plot_spacer() + plot_spacer())) +
  plot_layout(heights = c(89,11))
l2_prec_at_recall20_knowledge_overall_heatmap_fig <- l2_prec_at_recall20_knowledge_heatmap + l2_prec_at_recall20_knowledge_overall_right_half +
  plot_layout(ncol = 2)
ggsave("/Users/kayla/norm_for_RNAseq_coexp/plots/sra_l2_prec_at_recall20_knowledge_overall_heatmap_fig.png", 
       plot = l2_prec_at_recall20_knowledge_overall_heatmap_fig, width = 18, height = 9)
```