---
title: "gtex_resampling_heatmaps"
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(knitr)
library(rmarkdown)
library(patchwork)
library(ggfittext)
library(pheatmap)
library(ggplotify)
library(Matrix)
```

# GTEx resampling data
```{r include=FALSE}
rnr <- read_delim("../data/2020-03-19_gtex_resampling_naive_results.txt",
                    delim = "\t", col_names = T)
rnpr <- read_delim("../data/2020-03-19_prec_recall_gtex_resampling_naive_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)
rkr <- read_delim("../data/2020-03-19_gtex_resampling_knowledge_results.txt",
                    delim = "\t", col_names = T)
rkpr <- read_delim("../data/2020-03-19_prec_recall_gtex_resampling_knowledge_results.txt",
                   delim = "\t", col_names = T) %>% 
  filter(recall == 20)

rnr$method <- gsub("quantile", "QNT", rnr$method)
rnr$method <- gsub("wTO", "WTO", rnr$method)
rnpr$method <- gsub("quantile", "QNT", rnpr$method)
rnpr$method <- gsub("wTO", "WTO", rnpr$method)

rkr$method <- gsub("quantile", "QNT", rkr$method)
rkr$method <- gsub("wTO", "WTO", rkr$method)
rkpr$method <- gsub("quantile", "QNT", rkpr$method)
rkpr$method <- gsub("wTO", "WTO", rkpr$method)
```

# Method Codes
```{r}
method_codes <- read_delim("../data/2020-03-19_method_codes.txt",
                           delim = "\t", col_names = T)
method_codes$method <- gsub("quantile", "QNT", method_codes$method)
method_codes$method <- gsub("wTO", "WTO", method_codes$method)
```

# Functions
```{r include=FALSE}
#functions to build heatmap
get_times_greater_than_matrix <- function(meth_df){
  #df should be methods_* df (each row is performance on given dataset)
  counts_output <- matrix(rep(0, 900), nrow = 30, ncol = 30)
  colnames(counts_output) <- colnames(meth_df)
  rownames(counts_output) <- colnames(meth_df)
  
  for(num in 1:30){
  a <- pull(meth_df, num)
  for(val in 1:30){
    if (num == val){
      counts_output[val, num] <- 0.5
      next
    }
    b <- pull(meth_df, val)
    s <- sum(a < b)
    s <- s/nrow(meth_df)
    counts_output[val, num] <- s
  }
  }
  return(counts_output)
}

get_significance_matrix <- function(df, performance_col_position, method_col_position){
  #df tidy format with method as a column and performance as a column
  sig_output <- pairwise.wilcox.test(x = pull(df, performance_col_position),
                                     g = pull(df, method_col_position),
                                     paired = TRUE,
                                     p.adjust.method = "BH")$p.value
  
  #add row/col to make 30 by 30
  CLR <- sig_output[1,]
  CLR[1] <- NA
  sig_output <- rbind(CLR, sig_output)
  WTO <- sig_output[,29]
  WTO[30] <- NA
  sig_output <- cbind(sig_output, WTO)
  
  #make symmetric
  diag(sig_output) <- 1
  sig_output <- Matrix::forceSymmetric(sig_output, uplo = "L")
  sig_output <- as.matrix(sig_output)
  #replace p vals with sig/not sig
  sig_wilcox_gtex_naive <- ifelse(sig_output < 0.01, "*", " ")
}

get_method_times_sig_greater <- function(times_matrix, sig_matrix){
  #times_matrix is output of get_times_greater_than_matrix
  #sig_matrix is output of get_significance_matrix
  #make times_matrix into tibble and get times method_one > method_two
  times_greater_than_tibble <- as_tibble(times_matrix)
  times_greater_than_tibble$method_one <- colnames(times_matrix)
  times_greater_than_tibble <- times_greater_than_tibble %>% 
    gather(key = method_two, value = times_method_one_is_greater_than_method_two, 1:30)
  #make sig_matrix into tibble and get times corrected wilcox p value was
  #significant between method_one and method_two
  sig_wilcox_tibble <-  as_tibble(sig_matrix)
  sig_wilcox_tibble$method_one <- colnames(sig_matrix)
  sig_wilcox_tibble <- sig_wilcox_tibble %>%
    gather(key = method_two, value = significance, 1:30)
  sig_wilcox_tibble$significance <- ifelse(sig_wilcox_tibble$significance == "*",
                                           T, F)
  
  #join above two tibbles into one
  greater_than_significance_tibble <- left_join(times_greater_than_tibble,
                                                sig_wilcox_tibble,
                                                by = c("method_one", "method_two"))
  #make T/F column designating whether method_one > method_two AND significant by 
  #corrected wilcox p value
  greater_than_significance_tibble$method_one_greater_than_and_sig <-
    ifelse(greater_than_significance_tibble$times_method_one_is_greater_than_method_two > 0.5 &
       greater_than_significance_tibble$significance == T, T, F)
  #summarize above info by method
  method_summary <- greater_than_significance_tibble %>%
    group_by(method_one) %>% 
    summarise(times_sig_and_greater = sum(method_one_greater_than_and_sig))
  #change col name from method_one to method
  colnames(method_summary) <- c("method", "times_sig_and_greater")
  
  return(method_summary)
}

get_heatmap_order <- function(method_summary, times_mat){
  #times_matrix is output of get_times_greater_than_matrix
  #method_summary is output of get_method_times_sig_greater
  heatmap_row_redness <- Matrix::rowSums(times_mat)
  heatmap_row_redness <- stack(heatmap_row_redness)
  colnames(heatmap_row_redness) <- c("rowsum", "method")
  heatmap_row_redness$rowsum <- as.numeric(heatmap_row_redness$rowsum)
  heatmap_row_redness$method <- as.character(heatmap_row_redness$method)
  method_summary <- left_join(method_summary, heatmap_row_redness, by = "method")
  heatmap_order <- method_summary %>% 
    arrange(desc(times_sig_and_greater), desc(rowsum)) %>% pull(method)
  return(heatmap_order)
}
```

```{r}
#make all naive plots
for (ss in unique(rnr$sample_num)){
  size_df <-  rnr %>% filter(sample_num == ss)
  
  size_methods_df <- size_df %>% 
    select(project, tissue, method, trial, log2_auprc_over_prior) %>% 
    spread(key = method, value = log2_auprc_over_prior) %>% 
    select(-project, -tissue, -trial)
  
  size_times_mat <- get_times_greater_than_matrix(size_methods_df)
  
  size_sig_mat <- get_significance_matrix(size_df, 6, 3)
  
  size_summary <- get_method_times_sig_greater(size_times_mat, size_sig_mat)
  
  heatmap_order <- get_heatmap_order(size_summary, size_times_mat)
  
  #reorder matrices by heatmap order
  size_times_mat <- size_times_mat[heatmap_order,]
  size_times_mat <- size_times_mat[,heatmap_order]
  size_sig_mat <- size_sig_mat[heatmap_order,]
  size_sig_mat <- size_sig_mat[,heatmap_order]
  
  #MAKE FIGURE
  
  #PLOT PARTS
  
  #naive plot parts
  heatmap <- pheatmap(size_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = size_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
  #change heatmap to ggobject
  heatmap <- as.ggplot(heatmap)

  labels_plot <- method_codes %>% 
    ggplot(aes(x = key, y = factor(method, levels = rev(heatmap_order)), fill = value, label = value))+
    geom_tile(color = "white", size = 0.5) +
    #geom_text(aes(label = value)) +
    scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.text = element_blank(), 
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          plot.margin = margin(2,0,5,0)) +
    geom_fit_text() +
    guides(fill = F)
 
  bar_plot <- size_summary %>% 
    ggplot(aes(x = factor(method, levels = rev(heatmap_order)), y = times_sig_and_greater)) +
    geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
    geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
    geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
    geom_col(fill = "lightgray") +
    xlab("Method") +
    ylab("Times Significantly Greater Than Other Methods") +
    geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
    scale_y_continuous(limits = c(0,30))+
    coord_flip() +
    theme(panel.background = element_rect(fill = "white"), 
          panel.grid.minor = element_blank(), 
          panel.grid.major = element_blank(),
          text = element_text(size = 14),
          axis.text.y = element_blank(),
          axis.title = element_blank(),
          plot.margin = margin(2,0.5,5,0.5)) +
    guides(fill = F)
  
  #PUT FIGURE TOGETHER
  
  right_half <- ((labels_plot + bar_plot) / (plot_spacer() + plot_spacer())) + plot_layout(heights = c(89,11))
  
  overall_heatmap_fig <- heatmap + right_half + plot_layout(ncol = 2)
  
  ggsave(paste0("/Users/kayla/norm_for_RNAseq_coexp/plots/gtex_resampling_",  ss, "_sample_naive_heatmap_fig.png"), 
        plot = overall_heatmap_fig, width = 18, height = 9)
}
```

```{r}
#make all knowledge plots
for (ss in unique(rkr$sample_num)){
  size_df <-  rkr %>% filter(sample_num == ss)
  
  size_methods_df <- size_df %>% 
    select(project, tissue, method, trial, log2_auprc_over_prior) %>% 
    spread(key = method, value = log2_auprc_over_prior) %>% 
    select(-project, -tissue, -trial)
  
  size_times_mat <- get_times_greater_than_matrix(size_methods_df)
  
  size_sig_mat <- get_significance_matrix(size_df, 6, 3)
  
  size_summary <- get_method_times_sig_greater(size_times_mat, size_sig_mat)
  
  heatmap_order <- get_heatmap_order(size_summary, size_times_mat)
  
  #reorder matrices by heatmap order
  size_times_mat <- size_times_mat[heatmap_order,]
  size_times_mat <- size_times_mat[,heatmap_order]
  size_sig_mat <- size_sig_mat[heatmap_order,]
  size_sig_mat <- size_sig_mat[,heatmap_order]
  
  #MAKE FIGURE
  
  #PLOT PARTS
  
  #knowledge plot parts
  heatmap <- pheatmap(size_times_mat, cluster_rows = F, cluster_cols = F,
                                         display_numbers = size_sig_mat, fontsize_number = 14, legend = F,
                                         show_rownames = F, show_colnames = T)
  #change heatmap to ggobject
  heatmap <- as.ggplot(heatmap)

  labels_plot <- method_codes %>% 
    ggplot(aes(x = key, y = factor(method, levels = rev(heatmap_order)), fill = value, label = value))+
    geom_tile(color = "white", size = 0.5) +
    #geom_text(aes(label = value)) +
    scale_fill_manual(values = c(" " = "#eff3ff", "CPM" = "#bdd7e7",
                    "RPKM" = "#6baed6", "TPM" = "#2171b5",
                    "  " = "#edf8e9", "QNT" = "#bae4b3",  "TMM" = "#74c476",
                    "UQ" = "#238b45", "   " = "#feedde",
                    "CLR" = "#fdbe85", "WTO" = "#fd8d3c")) +
    theme(panel.background = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.text = element_blank(), 
          axis.ticks = element_blank(),
          axis.title = element_blank(),
          plot.margin = margin(2,0,5,0)) +
    geom_fit_text() +
    guides(fill = F)
 
  bar_plot <- size_summary %>% 
    ggplot(aes(x = factor(method, levels = rev(heatmap_order)), y = times_sig_and_greater)) +
    geom_hline(yintercept = 10, color = "#999999", size = 0.1) +
    geom_hline(yintercept = 20, color = "#999999", size = 0.1) +
    geom_hline(yintercept = 30, color = "#999999", size = 0.1) +
    geom_col(fill = "lightgray") +
    xlab("Method") +
    ylab("Times Significantly Greater Than Other Methods") +
    geom_text(aes(label = times_sig_and_greater), hjust = -0.1, color = "black") +
    scale_y_continuous(limits = c(0,30))+
    coord_flip() +
    theme(panel.background = element_rect(fill = "white"), 
          panel.grid.minor = element_blank(), 
          panel.grid.major = element_blank(),
          text = element_text(size = 14),
          axis.text.y = element_blank(),
          axis.title = element_blank(),
          plot.margin = margin(2,0.5,5,0.5)) +
    guides(fill = F)
  
  #PUT FIGURE TOGETHER
  
  right_half <- ((labels_plot + bar_plot) / (plot_spacer() + plot_spacer())) + plot_layout(heights = c(89,11))
  
  overall_heatmap_fig <- heatmap + right_half + plot_layout(ncol = 2)
  
  ggsave(paste0("/Users/kayla/norm_for_RNAseq_coexp/plots/gtex_resampling_",  ss, "_sample_knowledge_heatmap_fig.png"), 
        plot = overall_heatmap_fig, width = 18, height = 9)
}
```


